### ISSUE TITLE
新用户注册第一次登录异常

### ISSUE THREAD

**Issue by xiaosong520** [jpush/jchat-android#116]
用户注册之后进行登录操作，代码执行到这里报异常，好像是提示数据表报空，参照demo这样的逻辑处理的。为什么会报空呢？
JMessageClient.register(Jchat_Uid, Jchat_Pwd, new BasicCallback() {
                                    @Override
                                    public void gotResult(final int status, final String desc) {
                                        if (status == 0) {//注册成功
                                            JMessageClient.login(Jchat_Uid, Jchat_Pwd, new BasicCallback() {
                                                @Override
                                                public void gotResult(final int status, String desc) {
                                                    if (status == 0) {//注册完成，重新登录成功
                                                        String username = JMessageClient.getMyInfo().getUserName();
                                                        String appKey = JMessageClient.getMyInfo().getAppKey();
                                                        UserEntry user = UserEntry.getUser(username, appKey);
                                                        if (null == user) {
                                                            user = new UserEntry(username, appKey);
                                                            user.save();
                                                        }
                                                     ...

**Comment by KenChoi1992** [comment]
@xiaosong520  这个应该是 MyInfo 还没拿到，我看看

**Comment by KenChoi1992** [comment]
@xiaosong520 我试了一下可以的，并没有报错。

**Comment by KenChoi1992** [comment]
@xiaosong520 你现在拉一下代码，然后跑一下，如果有报错，可以贴上日志

**Comment by xiaosong520** [comment]
@KenChoi1992  提示是这段出错的：
UserEntry user = UserEntry.getUser(username, appKey);
                            if (user == null) {
                                user = new UserEntry(username, appKey);
                                user.save();
                            }
是登录成功之后拿不到UserEntry导致空指针异常。
错误日志：
E/JMessage: [CommonUtils] error occured in users callback, msg = Attempt to invoke virtual method com.activeandroid.TableInfo com.activeandroid.ModelInfo.getTableInfo(java.lang.Class)' on a null object reference
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method com.activeandroid.TableInfo com.activeandroid.ModelInfo.getTableInfo(java.lang.Class)' on a null object reference
W/System.err:     at com.activeandroid.Cache.getTableName(Cache.java:156)
W/System.err:     at com.activeandroid.query.From.addFrom(From.java:169)
W/System.err:     at com.activeandroid.query.From.toSql(From.java:250)
W/System.err:     at com.activeandroid.query.From.executeSingle(From.java:311)
W/System.err:     at jchat.database.UserEntry.getUser(UserEntry.java:31)
